# Generated by Django 5.0.7 on 2024-08-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='size',
        ),
    ]
