# Generated by Django 5.0.7 on 2024-08-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_review_reviewer'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
